In [17]:
import numpy as np
a = np.arange(9).reshape(3,3) # a range is just like a range in for loop if we just put 9 its the end number we can put starting number as well i.e 1,9
# we can also put kike 1,9,2 the 2 is the step
b =  np.arange(9).reshape(3,3)
np.add(a,b)



array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [18]:
import numpy as np
a = np.arange(9).reshape(3,3)
b =  np.arange(9).reshape(3,3)
np.multiply(a,b)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [52]:
import numpy as np
print("before transpose:")
a = np.arange(1,25).reshape(6,4)
print(a)
# use the transpose function
print("after transpose:")
b= np.transpose(a)
print(b)


before transpose:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
after transpose:
[[ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]
 [ 4  8 12 16 20 24]]


In [68]:
import pandas as pd
l = [ "hello", "jam","hotel","ram","paul","andy"]
df = pd.DataFrame(l)
df.sort_values(by = 0)

0
5   andy
0  hello
2  hotel
1    jam
4   paul
3    ram

In [83]:
#method1
import string
s = "hello , how r u. i hope ur doing well !. How is Andy?. Andys email was andy@gmail.com."

punct = string.punctuation #punctualtion is function of class string which gives a list of punctuation
"""now to remove punctuation we will use translate method and translate method needs a table
to create a table we need maketrans method this creates a table"""
#syntax - s.maketrans(old string,new string u want to replace with,string u want to remove )
t= s.maketrans("","",punct) # the reason i put space bcs i dont want any chater other then punctuations to rbe removed
#syntax for translate - s.translate(tablename) - here the table name is t u can put any name in place of t
s.translate(t) # this will remove all the 


'hello  how r u i hope ur doing well  How is Andy Andys email was andygmailcom'

In [104]:
#method 2
import string
punctuations = string.punctuation

def Punctuation(string):
    global punctuations 
    
    
    
    for x in string:
        if x in punctuations:
            string = string.replace(x, "")
    print(string)
            
    







strings = "Welcome???@@##$ to#$% Geeks%$^for$%^&Geeks"
Punctuation(strings)




Welcome to GeeksforGeeks
